### ISSUE TITLE
question

### ISSUE THREAD

**Issue by tavorazo** [tavorazo/learning#6]
how I can write a "do while" in Go?

it is correct?

how I can write a do while?

   for value := 0;; {
        value++
        fmt.Println(value)
        if condition {
            break
        }

**Comment by solojavier** [comment]
As a recommendation use the question as title for the issue... that way it can be searched later...

there are 3 options: 

```
// Like a C for
for init; condition; post { }

// Like a C while
for condition { }

// Like a C for(;;)
for { }
```

More info here: https://golang.org/doc/effective_go.html
