### ISSUE TITLE
polimorfismo OOP

### ISSUE THREAD

**Issue by tavorazo** [tavorazo/learning#7]
tengo unas dudas sobre polimosfirmo. 

Me pidieron que hiciera también la comparación de Go en OOP, ahorita voy en polimosfirmo.

Explico que entiendo de eso y después el detalle que tengo. 

si tienes varias clases con un mismo método y estas heredan de una clase padre. El polimorfismo es que puedes crear un método general para todas esas clases. cierto? 

Pero leí que se tienen 3 tipos de polimosfirmos y empiezo a confundirme. No se Java, solo quiero entender su uso para introducirme mas a estos temas.

**Comment by solojavier** [comment]
Cuales 3 tipos? En este articulo por ejemplo maneja 2 tipos: http://c2.com/cgi/wiki?PolyMorphism

Basicamente polimorfismo se refiere a la capacidad de objetos de reaccionar de la misma manera aun siendo de diferentes formas o asi lo entiendo yo.

Un ejemplo es el que mencionas, donde todos los hijos o subtipos de un objeto responden a un mismo metodo, entonces en una funcion, le puedes pasar cualquiera de esos objetos y siempre se comporta igual...

Otra manera es en la que muchos objetos definen el mismo metodo, pero que no necesariamente son hijos o herencia... por decir el methdo "to_string" donde esperarias de cualquier objeto que fuera una representacion de si mismo en texto...

No se si me doy a entender o quieres mas detalle :)..

En Go, se puede lograr el polimorfismo con las interfaces, ya que no existe la herencia.

**Comment by tavorazo** [comment]
Gracias. 

Es que leí que existen 3 maneras o tipos de polimosfirmo. El de sobre-escritura que creo es el que mencionas con "to_string" donde se usan los mismos métodos pero pueden variar los argumentos del método y no necesariamente pueden ser clases heredadas.

Otro es el de sobre-carga, que es el que me dices de ejemplo al principio y otro según es el de "ligadura dinamica" que... no entiendo...   se me hace confuso su uso

**Comment by solojavier** [comment]
Sobre carga es cuando nombras dos metodos iguales, pero con diferentes parametros
